"""Gold97 move metadata missing or different in the generic Gen I table."""


# (move type, base power) from the cartridge's Crystal-era move table.  Moves
# omitted here use the shared table; these entries cover Gen II additions and
# the early moves whose type or power changed between generations.
MOVE_OVERRIDES = {
    "KARATE CHOP": ("FIGHTING", 50), "GUILLOTINE": ("NORMAL", 0),
    "GUST": ("FLYING", 40), "WING ATTACK": ("FLYING", 60),
    "SAND ATTACK": ("GROUND", 0), "DOUBLE EDGE": ("NORMAL", 120),
    "BITE": ("DARK", 60), "SONICBOOM": ("NORMAL", 20),
    "DRAGON RAGE": ("DRAGON", 40), "DIG": ("GROUND", 60),
    "PSYCHIC M": ("PSYCHIC", 90), "NIGHT SHADE": ("GHOST", 1),
    "SELFDESTRUCT": ("NORMAL", 200), "EXPLOSION": ("NORMAL", 250),
    "CROSS CUTTER": ("BUG", 50), "SKETCH": ("NORMAL", 0),
    "TRIPLE KICK": ("FIGHTING", 10), "THIEF": ("DARK", 40),
    "SPIDER WEB": ("BUG", 0), "MIND READER": ("NORMAL", 0),
    "NIGHTMARE": ("GHOST", 0), "FLAME WHEEL": ("FIRE", 60),
    "SNORE": ("NORMAL", 40), "CURSE": ("CURSE_T", 0),
    "FLAIL": ("NORMAL", 1), "CONVERSION2": ("NORMAL", 0),
    "AEROBLAST": ("FLYING", 100), "COTTON SPORE": ("GRASS", 0),
    "REVERSAL": ("FIGHTING", 1), "SPITE": ("GHOST", 0),
    "POWDER SNOW": ("ICE", 40), "PROTECT": ("NORMAL", 0),
    "MACH PUNCH": ("FIGHTING", 40), "SCARY FACE": ("NORMAL", 0),
    "FAINT ATTACK": ("DARK", 60), "SWEET KISS": ("NORMAL", 0),
    "BELLY DRUM": ("NORMAL", 0), "SLUDGE BOMB": ("POISON", 90),
    "MUD SLAP": ("GROUND", 20), "OCTAZOOKA": ("WATER", 65),
    "SPIKES": ("GROUND", 0), "ZAP CANNON": ("ELECTRIC", 100),
    "FORESIGHT": ("NORMAL", 0), "DESTINY BOND": ("GHOST", 0),
    "PERISH SONG": ("NORMAL", 0), "ICY WIND": ("ICE", 55),
    "DETECT": ("FIGHTING", 0), "BONE RUSH": ("GROUND", 25),
    "LOCK ON": ("NORMAL", 0), "OUTRAGE": ("DRAGON", 90),
    "SANDSTORM": ("ROCK", 0), "GIGA DRAIN": ("GRASS", 60),
    "ENDURE": ("NORMAL", 0), "CHARM": ("NORMAL", 0),
    "ROLLOUT": ("ROCK", 30), "FALSE SWIPE": ("NORMAL", 40),
    "SWAGGER": ("NORMAL", 0), "MILK DRINK": ("NORMAL", 0),
    "SPARK": ("ELECTRIC", 65), "FURY CUTTER": ("BUG", 10),
    "STEEL WING": ("STEEL", 70), "MEAN LOOK": ("NORMAL", 0),
    "ATTRACT": ("NORMAL", 0), "SLEEP TALK": ("NORMAL", 0),
    "HEAL BELL": ("NORMAL", 0), "RETURN": ("NORMAL", 1),
    "PRESENT": ("NORMAL", 1), "FRUSTRATION": ("NORMAL", 1),
    "SAFEGUARD": ("NORMAL", 0), "PAIN SPLIT": ("NORMAL", 0),
    "SACRED FIRE": ("FIRE", 100), "MAGNITUDE": ("GROUND", 1),
    "DYNAMICPUNCH": ("FIGHTING", 100), "MEGAHORN": ("BUG", 120),
    "DRAGONBREATH": ("DRAGON", 60), "BATON PASS": ("NORMAL", 0),
    "ENCORE": ("NORMAL", 0), "PURSUIT": ("DARK", 40),
    "RAPID SPIN": ("NORMAL", 20), "SWEET SCENT": ("NORMAL", 0),
    "IRON TAIL": ("STEEL", 100), "METAL CLAW": ("STEEL", 50),
    "VITAL THROW": ("FIGHTING", 70), "MORNING SUN": ("NORMAL", 0),
    "SYNTHESIS": ("GRASS", 0), "MOONLIGHT": ("NORMAL", 0),
    "HIDDEN POWER": ("NORMAL", 1), "CROSS CHOP": ("FIGHTING", 100),
    "TWISTER": ("DRAGON", 40), "RAIN DANCE": ("WATER", 0),
    "SUNNY DAY": ("FIRE", 0), "CRUNCH": ("DARK", 80),
    "MIRROR COAT": ("PSYCHIC", 1), "PSYCH UP": ("NORMAL", 0),
    "EXTREMESPEED": ("NORMAL", 80), "ANCIENTPOWER": ("ROCK", 60),
    "SHADOW BALL": ("GHOST", 80), "FUTURE SIGHT": ("PSYCHIC", 80),
    "ROCK SMASH": ("FIGHTING", 20), "WHIRLPOOL": ("WATER", 15),
    "BEAT UP": ("DARK", 10), "COIN HURL": ("NORMAL", 40),
    "MEGAPHONE": ("NORMAL", 0), "ROCK HEAD": ("ROCK", 90),
}
