"""Canonical first 251 species names from PokeAPI pokemon_species.csv.

https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_species.csv

Compare normalized cartridge names, never numeric IDs: Reforged replaces entries.
Unknown or ambiguous names are not eligible for an automatic wild catch.
"""

ORIGINAL_251 = frozenset("""
BULBASAUR IVYSAUR VENUSAUR CHARMANDER CHARMELEON CHARIZARD SQUIRTLE WARTORTLE BLASTOISE CATERPIE
METAPOD BUTTERFREE WEEDLE KAKUNA BEEDRILL PIDGEY PIDGEOTTO PIDGEOT RATTATA RATICATE
SPEAROW FEAROW EKANS ARBOK PIKACHU RAICHU SANDSHREW SANDSLASH NIDORAN-F NIDORINA
NIDOQUEEN NIDORAN-M NIDORINO NIDOKING CLEFAIRY CLEFABLE VULPIX NINETALES JIGGLYPUFF WIGGLYTUFF
ZUBAT GOLBAT ODDISH GLOOM VILEPLUME PARAS PARASECT VENONAT VENOMOTH DIGLETT
DUGTRIO MEOWTH PERSIAN PSYDUCK GOLDUCK MANKEY PRIMEAPE GROWLITHE ARCANINE POLIWAG
POLIWHIRL POLIWRATH ABRA KADABRA ALAKAZAM MACHOP MACHOKE MACHAMP BELLSPROUT WEEPINBELL
VICTREEBEL TENTACOOL TENTACRUEL GEODUDE GRAVELER GOLEM PONYTA RAPIDASH SLOWPOKE SLOWBRO
MAGNEMITE MAGNETON FARFETCHD DODUO DODRIO SEEL DEWGONG GRIMER MUK SHELLDER
CLOYSTER GASTLY HAUNTER GENGAR ONIX DROWZEE HYPNO KRABBY KINGLER VOLTORB
ELECTRODE EXEGGCUTE EXEGGUTOR CUBONE MAROWAK HITMONLEE HITMONCHAN LICKITUNG KOFFING WEEZING
RHYHORN RHYDON CHANSEY TANGELA KANGASKHAN HORSEA SEADRA GOLDEEN SEAKING STARYU
STARMIE MR-MIME SCYTHER JYNX ELECTABUZZ MAGMAR PINSIR TAUROS MAGIKARP GYARADOS
LAPRAS DITTO EEVEE VAPOREON JOLTEON FLAREON PORYGON OMANYTE OMASTAR KABUTO
KABUTOPS AERODACTYL SNORLAX ARTICUNO ZAPDOS MOLTRES DRATINI DRAGONAIR DRAGONITE MEWTWO
MEW CHIKORITA BAYLEEF MEGANIUM CYNDAQUIL QUILAVA TYPHLOSION TOTODILE CROCONAW FERALIGATR
SENTRET FURRET HOOTHOOT NOCTOWL LEDYBA LEDIAN SPINARAK ARIADOS CROBAT CHINCHOU
LANTURN PICHU CLEFFA IGGLYBUFF TOGEPI TOGETIC NATU XATU MAREEP FLAAFFY
AMPHAROS BELLOSSOM MARILL AZUMARILL SUDOWOODO POLITOED HOPPIP SKIPLOOM JUMPLUFF AIPOM
SUNKERN SUNFLORA YANMA WOOPER QUAGSIRE ESPEON UMBREON MURKROW SLOWKING MISDREAVUS
UNOWN WOBBUFFET GIRAFARIG PINECO FORRETRESS DUNSPARCE GLIGAR STEELIX SNUBBULL GRANBULL
QWILFISH SCIZOR SHUCKLE HERACROSS SNEASEL TEDDIURSA URSARING SLUGMA MAGCARGO SWINUB
PILOSWINE CORSOLA REMORAID OCTILLERY DELIBIRD MANTINE SKARMORY HOUNDOUR HOUNDOOM KINGDRA
PHANPY DONPHAN PORYGON2 STANTLER SMEARGLE TYROGUE HITMONTOP SMOOCHUM ELEKID MAGBY
MILTANK BLISSEY RAIKOU ENTEI SUICUNE LARVITAR PUPITAR TYRANITAR LUGIA HO-OH
CELEBI
""".split())


def _normal(name):
    name = name.upper().replace("♀", "F").replace("♂", "M")
    return "".join(character for character in name if character.isalnum())


ORIGINAL_NORMALIZED = frozenset(_normal(name) for name in ORIGINAL_251)


def hack_exclusive(name, verified_rom=True):
    """Only a verified Reforged ROM and a readable novel name permit wild capture."""
    value = _normal(name or "")
    return bool(verified_rom and value and not value.startswith("MON")
                and "UNKNOWN" not in value and "?" not in str(name)
                and value not in ORIGINAL_NORMALIZED)
