"""Stream PyBoy's per-frame sound buffer to the local audio device."""

from __future__ import annotations

import logging

import pygame


LOGGER = logging.getLogger(__name__)
AUDIO_SAMPLE_RATE = 48_000
AUDIO_CHANNELS = 2
AUDIO_BUFFER = 1_024
AUDIO_CHUNK_SECONDS = 0.1
MAX_PENDING_SECONDS = 0.2


def pre_init(sample_rate: int = AUDIO_SAMPLE_RATE) -> None:
    """Set pygame's mixer format before ``pygame.init`` initializes it."""
    try:
        pygame.mixer.pre_init(
            frequency=sample_rate,
            size=-8,
            channels=AUDIO_CHANNELS,
            buffer=AUDIO_BUFFER,
        )
    except pygame.error:
        # AudioSink will retry initialization and disable itself if the device is
        # unavailable. Display-only runs should still work in that situation.
        LOGGER.debug("pygame mixer pre-init failed", exc_info=True)


class AudioSink:
    """Buffer PyBoy samples and play them as a continuous mixer stream.

    PyBoy gives us roughly one 16 ms buffer per frame. Playing each one directly
    leaves a scheduling gap at every boundary; keeping a 100 ms chunk queued gives
    the mixer enough work to cross those boundaries cleanly.
    """

    def __init__(self, sample_rate: int = AUDIO_SAMPLE_RATE):
        self.enabled = False
        self.muted = False
        self.channel = None
        self._pending = bytearray()
        self._chunk_bytes = int(sample_rate * AUDIO_CHUNK_SECONDS) * AUDIO_CHANNELS
        self._max_pending_bytes = int(sample_rate * MAX_PENDING_SECONDS) * AUDIO_CHANNELS
        try:
            current = pygame.mixer.get_init()
            expected = (sample_rate, -8, AUDIO_CHANNELS)
            if current != expected:
                if current:
                    pygame.mixer.quit()
                pygame.mixer.init(
                    frequency=sample_rate,
                    size=-8,
                    channels=AUDIO_CHANNELS,
                    buffer=AUDIO_BUFFER,
                )
            self.channel = pygame.mixer.Channel(0)
            self.channel.set_volume(0.0 if self.muted else 1.0)
            self.enabled = True
        except pygame.error:
            LOGGER.warning("Audio is unavailable; continuing without sound.")

    def feed(self, emulator) -> None:
        """Append the samples generated by the most recent emulator frame."""
        if not self.enabled:
            return
        try:
            samples = emulator.sound.ndarray
            if samples.size == 0:
                return
            self._pending.extend(samples.tobytes())
            if len(self._pending) > self._max_pending_bytes:
                # Fast-forward modes can produce samples faster than a real-time
                # speaker can consume them. Drop whole stereo frames, never bytes.
                excess = len(self._pending) - self._max_pending_bytes
                del self._pending[: excess - (excess % AUDIO_CHANNELS)]
            self._pump()
        except Exception:
            # A disabled PyBoy sound buffer or a device disappearing during a run
            # should not take down the emulator window.
            self.enabled = False
            LOGGER.warning("Audio playback stopped; continuing without sound.")

    def toggle_mute(self) -> bool:
        """Toggle playback without interrupting the emulator sound buffer."""
        self.muted = not self.muted
        if self.channel is not None:
            self.channel.set_volume(0.0 if self.muted else 1.0)
        return self.muted

    def set_muted(self, muted: bool) -> None:
        """Apply a persisted mute choice after recreating the audio sink."""
        self.muted = bool(muted)
        if self.channel is not None:
            self.channel.set_volume(0.0 if self.muted else 1.0)

    def _pump(self) -> None:
        if len(self._pending) < self._chunk_bytes:
            return
        if self.channel.get_busy() and self.channel.get_queue() is not None:
            return
        chunk = bytes(self._pending[: self._chunk_bytes])
        del self._pending[: self._chunk_bytes]
        sound = pygame.mixer.Sound(buffer=chunk)
        if self.channel.get_busy():
            self.channel.queue(sound)
        else:
            self.channel.play(sound)

    def close(self) -> None:
        if self.channel is not None:
            self.channel.stop()
        self._pending.clear()
